### PR TITLE
First try with simple redis as caching layer.

### PR DESCRIPTION
**Pull request by nvtkaszpir**
Actually my first try with redis, but it works.

### CODE REVIEW

**Comment by pmazurek** [comment]
I am afraid adding redis as a dependency is a little too much. I think it would be ok to just store the data somewhere in a file.

**Comment by pmazurek** [comment]
I mean this would require someone to actually spin a whole database in order to use just one functionality. It seems like a heavy overkill. Nonetheless I'm tempted to merge this PR, because its strong work, and then just switch redis to be something file-based.

**Comment by pmazurek** [comment]
Ok I'm merging it, once I'm done modifying it, I'll release a new version. Thank you so much for this contribution @nvtkaszpir , amazing work!

**Comment by nvtkaszpir** [comment]
Hm, you're right, redis may be an overkill and plain files should be enough.
Now when you mentioned it I think this should go to separate branch or as separate module for caching.

Why introducing redis:
With certain amount of people we sometimes start to hit AWS API calls limits. 
So I was thinking about using shared database among people at work to store data, and this is a first attempt to implement such storage, there are no critical data.
In general we would set up separate redis server, a worker to query AWS regions once a minute (should be enough), so people would be able to get require data faster.
Yes, this may be an overkill for single user.

**Pull request merged**
