### PR TITLE
Add instance Id to fuzzy list finder.

### PR DESCRIPTION
**Pull request by andrefsp**
This PR adds the instance ID to the fuzzy list.

### CODE REVIEW

**Comment by egidijus** [comment]
<3

**Comment by rszalski** [comment]
I've resolved conflicts since `master` got a bit ahead.

**Comment by rszalski** [comment]
@andrefsp I'll merge this once the tests are fixed as this change looks good :)

**Comment by pmazurek** [comment]
Fixed tests and merging this, thanks for the contribution Sir!

**Pull request merged**
